import './style.css';
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const supabase = supabaseUrl && supabaseKey ? createClient(supabaseUrl, supabaseKey) : null;
let currentUser = null;

async function ensureSession(){
  if(!supabase) return null;
  const { data:{ session } } = await supabase.auth.getSession();
  if(session?.user){ currentUser=session.user; return currentUser; }
  const { data, error } = await supabase.auth.signInAnonymously();
  if(error){ console.error('Supabase anonymous sign-in failed', error); return null; }
  currentUser=data.user; return currentUser;
}
ensureSession();

const modal=document.querySelector('#finder'),form=document.querySelector('#finderForm'),results=document.querySelector('#results');
const CURRENCIES=['EUR','GEL','USD','GBP','CHF','CAD','AUD','JPY','Other'];
const symbols={EUR:'€',GEL:'₾',USD:'$',GBP:'£',CHF:'CHF ',CAD:'C$',AUD:'A$',JPY:'¥'};
const evidenceNote='Ideas are practical workplace suggestions informed by evidence on employee participation, social connection, workplace physical activity and healthy work design. They are not medical advice and outcomes vary by team.';
document.querySelector('[data-scroll]').onclick=()=>document.querySelector('#tools').scrollIntoView({behavior:'smooth'});
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openTool(b.dataset.open));document.querySelector('.close').onclick=closeModal;modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
function closeModal(){modal.classList.remove('show');modal.setAttribute('aria-hidden','true')}
const currencyField=`<label>Currency<select id="currency">${CURRENCIES.map(x=>`<option ${x==='EUR'?'selected':''}>${x}</option>`).join('')}</select><input id="customCurrency" class="conditional" placeholder="Type currency or symbol" hidden></label>`;
const budgetField=`<label>Available budget<input id="budget" type="number" min="0" value="300" required><span class="field-note">Enter your approximate total budget.</span></label>${currencyField}`;
const fields={
 engagement:{eyebrow:'ENGAGEMENT IDEA FINDER',title:'What does your team need?',sub:'Engagement is about connection, participation, recognition and energy around work. Describe the challenge in your own words or use a starting point.',html:`<label>Team size<input id="teamSize" type="number" min="1" value="25" required><span class="field-note">Enter the exact number of people.</span></label><label>Work format<select id="format"><option>In-office</option><option>Hybrid</option><option>Remote</option><option value="other">Other — write my own</option></select><input id="formatOther" class="conditional" placeholder="Describe your setup" hidden></label><label class="full">Main challenge<select id="challengePreset"><option value="connection">People don't interact enough</option><option value="energy">Low team energy</option><option value="recognition">People need more recognition</option><option value="new">New team / many new hires</option><option value="other">Other — write my own</option></select><textarea id="challengeText" placeholder="Describe the challenge, e.g. two departments rarely interact, attendance at events is low…"></textarea></label>${budgetField}<button class="primary full">Find engagement ideas →</button>`},
 wellbeing:{eyebrow:'WELLBEING IDEA FINDER',title:'What kind of support would help?',sub:'Wellbeing focuses on healthy work habits, recovery, social wellbeing and making support easier to access. It is different from engagement: the goal here is a healthier work experience, not simply more participation.',html:`<label>Team size<input id="teamSize" type="number" min="1" value="30" required></label><label>Work format<select id="format"><option>In-office</option><option>Hybrid</option><option>Remote</option><option value="other">Other — write my own</option></select><input id="formatOther" class="conditional" placeholder="Describe your setup" hidden></label><label class="full">Wellbeing goal<select id="goal"><option value="reset">Help people pause & recharge</option><option value="connection">Build social wellbeing</option><option value="learning">Build healthy work habits</option><option value="support">Make support more visible</option><option value="movement">Encourage accessible movement</option><option value="other">Other — write my own</option></select><span class="field-note">Choose the outcome you want to support — e.g. recovery, connection, movement or healthier work routines.</span><textarea id="goalOther" placeholder="Write your own wellbeing goal…"></textarea></label>${budgetField}<label class="full">Anything else we should consider?<textarea id="challengeText" placeholder="Example: busy quarter, distributed team, previous activities had low attendance…"></textarea></label><button class="primary full">Find wellbeing ideas →</button>`},
 activity:{eyebrow:'TEAM ACTIVITY FINDER',title:'Find activities your team will actually want to join',sub:'This tool is for shared experiences: sport, creative, social, learning, volunteering, food, outdoor or remote activities. Type exactly what you want — the suggestions will use your words.',html:`<label>Team size<input id="teamSize" type="number" min="2" value="20" required></label><label>Format<select id="format"><option>In-office</option><option>Hybrid</option><option>Remote</option><option>Off-site</option><option value="other">Other — write my own</option></select><input id="formatOther" class="conditional" placeholder="Describe the format" hidden></label><label>Time available<select id="time"><option value="short">20–45 minutes</option><option value="medium">1–2 hours</option><option value="long">Half/full day</option><option value="other">Other — write my own</option></select><input id="timeOther" class="conditional" placeholder="e.g. 3 hours" hidden></label>${budgetField}<label class="full">Goal or preferences<textarea id="challengeText" placeholder="Try: sport activity, outdoor, calm, competitive, creative, volunteering, food, remote game…"></textarea><span class="field-note">Free text is important here — write a theme, mood, accessibility need or a completely new idea.</span></label><button class="primary full">Find team activities →</button>`},
 onboarding:{eyebrow:'ONBOARDING HUB',title:'Build and track each new hire’s onboarding',sub:'Create an individual employee record, save checklist progress securely in your PeopleLab database and return later to continue. The dashboard shows completion percentages and monthly onboarding totals.',html:`<label>First name<input id="firstName" required placeholder="e.g. Alex"></label><label>Last name<input id="lastName" required placeholder="e.g. Morgan"></label><label>Role / job title<input id="role" placeholder="e.g. Customer Success Manager" required></label><label>Work setup<select id="format"><option>In-office</option><option>Hybrid</option><option>Remote</option><option value="other">Other — write my own</option></select><input id="formatOther" class="conditional" placeholder="Describe the setup" hidden></label><label>Checklist depth<select id="depth"><option value="light">Light — essentials only</option><option value="standard">Standard — first week + first month</option><option value="detailed">Detailed — preboarding to 30 days</option><option value="other">Other — write my own</option></select><input id="depthOther" class="conditional" placeholder="e.g. Preboarding + first 60 days" hidden></label><label>Start date<input id="start" type="date"></label><label class="full">Role-specific notes<textarea id="challengeText" placeholder="Example: activate Beehive, customer shadowing, regional intro, special equipment…"></textarea></label><button class="primary full">Create & save onboarding →</button><button type="button" id="showDashboard" class="secondary full">Open onboarding dashboard</button>`}
};
let activeTool='engagement';
function openTool(tool){activeTool=tool;const x=fields[tool];document.querySelector('#modalEyebrow').textContent=x.eyebrow;document.querySelector('#modalTitle').textContent=x.title;document.querySelector('#modalSub').textContent=x.sub;form.innerHTML=x.html;results.hidden=true;results.innerHTML='';modal.classList.add('show');modal.setAttribute('aria-hidden','false');wireCustoms();if(tool==='onboarding'){document.querySelector('#showDashboard').onclick=renderDashboard}form.onsubmit=e=>{e.preventDefault();generate(tool)}}
function wireCustoms(){[['currency','customCurrency'],['format','formatOther'],['time','timeOther'],['depth','depthOther']].forEach(([a,b])=>{const el=document.querySelector('#'+a),other=document.querySelector('#'+b);if(!el||!other)return;const fn=()=>{const show=el.value==='Other'||el.value==='other';other.hidden=!show};el.onchange=fn;fn()})}
const ideaLibrary=[
{type:'engagement',tags:'connection social hybrid remote office',name:'Random Coffee Pairings',why:'Low-pressure 1:1 or trio conversations help colleagues meet outside their usual project circle.',outcome:'Broader internal connections and more familiar faces across teams.',min:0,max:4,time:'20–30 min every 2–3 weeks',needs:['Calendar or pairing sheet','3 optional conversation prompts','Coffee/tea budget if desired'],steps:['Create random pairs or trios, mixing departments where possible.','Send a calendar invite with a clear note that the conversation is informal and no preparation is needed.','Add 2–3 prompts such as “What are you working on that others may not know about?”','For office teams, meet over coffee; for remote teams, use the normal video-call tool.','After two rounds, run a one-question pulse: “Should we keep this going?”'],tips:'Keep it optional and rotate slowly; forced socializing can defeat the purpose.'},
{type:'engagement',tags:'recognition appreciation morale',name:'Specific Thanks Wall',why:'It turns vague praise into visible, concrete recognition by naming the contribution and its impact.',outcome:'More visible appreciation and a better understanding of behind-the-scenes contributions.',min:0,max:2,time:'10 min setup + weekly habit',needs:['Physical board or shared digital board','Simple recognition template'],steps:['Create a board titled “Thanks for the impact.”','Use one format: “Thanks to ___ for ___; it helped ___.”','Invite anyone to add notes during the week.','Read 3–5 notes at a weekly meeting without turning it into a competition.','Archive highlights monthly so recognition does not disappear.'],tips:'Recognize specific work and helpful behavior, not popularity.'},
{type:'engagement',tags:'energy fun music office hybrid',name:'Micro-Experience Week',why:'Several tiny shared moments can refresh the week without asking everyone to attend one large event.',outcome:'A lighter team rhythm and more small opportunities for connection.',min:2,max:8,time:'10–15 min/day for one week',needs:['Five tiny activity prompts','Speaker or video-call audio','Optional small prizes/snacks'],steps:['Choose five different micro-moments: music, trivia, appreciation, movement and a creative prompt.','Monday: play a team-chosen song for 5 minutes using a licensed workplace music source or a normal streaming/video platform available to your team.','Tuesday: run 5-question trivia in slides or your chat tool.','Wednesday: do a 10-minute stretch or walk break with an accessible seated option.','Thursday: run a specific-thanks round. Friday: let the team vote on the favorite moment and repeat it next month.'],tips:'Do not make every day high-energy; mix quiet and social options.'},
{type:'engagement',tags:'new onboarding connection culture',name:'How We Work Lab',why:'Making unwritten team norms visible reduces guesswork for new and existing teammates.',outcome:'Clearer expectations around communication, meetings, feedback and focus time.',min:0,max:5,time:'60–75 min',needs:['Shared document or whiteboard','Facilitator','Four headings: communication, meetings, decisions, feedback'],steps:['Ask everyone to add one thing that helps them work well and one friction point.','Group answers under the four headings.','Discuss where expectations differ rather than trying to make everyone identical.','Agree on 5–7 practical team norms.','Publish a one-page “How we work” guide and revisit it after a month.'],tips:'Treat norms as experiments that can change.'},
{type:'wellbeing',tags:'reset stress calm focus recovery',name:'Protected Reset Hour',why:'Changing the work design can support recovery without adding another event to an already busy calendar.',outcome:'A predictable low-interruption period for focus, recovery or catching up.',min:0,max:0,time:'60 min',needs:['Calendar block','Team agreement on response expectations'],steps:['Choose one hour that creates the least operational risk.','Block it on team calendars and pause non-urgent internal meetings/messages.','Tell people they may use it for focused work, a walk, lunch or a quiet reset.','Managers model the boundary by avoiding non-urgent requests during the hour.','After 2–3 weeks, ask whether the time is useful and adjust.'],tips:'Do not frame it as therapy or require people to explain how they use the time.'},
{type:'wellbeing',tags:'movement sport physical activity walk office hybrid remote',name:'Walk & Talk / Move Break',why:'Accessible movement can be integrated into the workday and paired with social connection rather than requiring a formal fitness event.',outcome:'A short break from sitting plus optional informal connection.',min:0,max:3,time:'20–30 min',needs:['Safe walking route or indoor alternative','Calendar invite','Seated/low-mobility alternative'],steps:['Choose a safe short route or an indoor movement option.','Invite pairs or small groups and make participation optional.','Use one light conversation prompt; this is not a walking meeting for difficult decisions.','For remote staff, offer a phone/audio walk or a seated stretch option.','Collect quick feedback on accessibility and timing.'],tips:'Avoid pace, distance or competition targets; design for different mobility levels.'},
{type:'wellbeing',tags:'learning habits boundaries meetings focus',name:'Meeting Hygiene Experiment',why:'Improving a repeated part of work can have more practical value than adding a one-off wellbeing perk.',outcome:'Fewer unnecessary meetings and clearer expectations for focused work.',min:0,max:0,time:'2-week experiment',needs:['Simple meeting checklist','Calendar analytics if already available'],steps:['Agree on three rules, e.g. agenda required, 25/50-minute defaults, and “no meeting” if an async update works.','Let teams cancel or shorten meetings that do not need live discussion.','Protect one recurring focus block.','After two weeks, ask what improved and what created problems.','Keep only the rules the team found useful.'],tips:'The goal is better work design, not measuring individual productivity.'},
{type:'wellbeing',tags:'support resources mental health benefits',name:'Support Map',why:'Existing support is only useful if employees know what exists, what it is for and how to access it.',outcome:'Clearer awareness of benefits, People contacts and workplace support routes.',min:0,max:2,time:'45–60 min setup',needs:['One-page document or intranet page','Verified internal support information'],steps:['List available support: People contact, benefits, leave guidance, wellbeing resources and emergency procedures appropriate to your organization.','For each item, write what it is for, who can access it and the exact internal route to use it.','Remove jargon and outdated links.','Share it during onboarding and periodically in normal internal communications.','Review it quarterly with the responsible owner.'],tips:'Do not collect sensitive health information through this tool.'},
{type:'activity',tags:'sport sports physical outdoor competitive football soccer volleyball basketball',name:'Mini Sports Festival',why:'Several short stations give people choice instead of forcing the whole team into one sport.',outcome:'A lively shared experience with more ways to participate.',min:5,max:25,time:'1–2 hours',needs:['Safe venue','Cones/balls or venue equipment','Water','Score sheet','Non-playing roles'],steps:['Survey the team for 3–4 preferred activities and accessibility needs.','Create short stations such as penalty shots, target throw, table tennis, relay-style skill games or volleyball passing.','Make mixed teams and rotate every 10–15 minutes.','Offer referee, photographer, scorekeeper or cheer roles for people who do not want to play.','Finish with a fun team award based on collaboration, not only winning.'],tips:'Use a suitable venue/provider for sports and keep participation voluntary.'},
{type:'activity',tags:'sport sports physical calm yoga stretch movement',name:'Movement Taster Session',why:'A sampler lets people try different forms of movement without assuming everyone enjoys competitive sport.',outcome:'Inclusive movement and discovery of activities employees may want to repeat.',min:3,max:18,time:'45–60 min',needs:['Open room or suitable venue','Qualified instructor when appropriate','Water','Accessible alternatives'],steps:['Ask employees which low-pressure movement styles interest them.','Choose 2–3 short blocks such as mobility, dance basics, balance or gentle stretching.','Use an appropriate instructor/provider for coached physical sessions.','Explain that people can skip any movement and choose seated alternatives.','End with a vote on whether any format should return.'],tips:'Avoid fitness tests, body comparisons or performance pressure.'},
{type:'activity',tags:'sport sports outdoor walk nature scavenger',name:'City Photo Walk Challenge',why:'It combines light movement, teamwork and creativity without requiring athletic skill.',outcome:'Informal conversation, shared memories and a playful outdoor break.',min:0,max:8,time:'60–90 min',needs:['Safe route','Phone cameras','Prompt list','Meeting point'],steps:['Choose a safe public route and define clear boundaries.','Create 8 photo prompts such as “best team color,” “unexpected pattern,” or “something that represents collaboration.”','Split into small groups and give everyone the same finish time.','Return to the meeting point and show 1–2 favorite photos per team.','Let people vote for creative categories rather than speed.'],tips:'Do not reward risky shortcuts; accessibility and safe routes come first.'},
{type:'activity',tags:'sport sports indoor table tennis ping pong badminton',name:'Casual Racket Games Rotation',why:'Short doubles rotations can make sport social and flexible for mixed experience levels.',outcome:'Movement plus easy conversation in small groups.',min:6,max:25,time:'1–2 hours',needs:['Suitable venue','Table tennis/badminton equipment','Water','Simple rotation board'],steps:['Book a suitable venue and confirm equipment.','Ask about interest and accessibility before finalizing.','Use doubles or cooperative rally rounds rather than elimination brackets.','Rotate partners every 10–15 minutes so people mix.','Keep a social rest area for anyone taking a break or not playing.'],tips:'Keep scoring optional; the purpose is participation, not athletic ranking.'},
{type:'activity',tags:'creative art calm office hybrid',name:'Collaborative Poster Studio',why:'A hands-on creative task gives quieter and more outgoing teammates different ways to contribute.',outcome:'A shared artifact and relaxed conversation outside normal work tasks.',min:3,max:12,time:'60–90 min',needs:['Paper/canvas','Markers, magazines or digital whiteboard','Music if the team wants it'],steps:['Pick a playful prompt such as “Our team in 2030” or “The perfect workday.”','Set up materials and optionally play low-volume background music from your team’s usual streaming source.','Split into groups of 4–6 and give 35–45 minutes to create.','Each group presents for two minutes.','Display the work in the office or save the digital versions.'],tips:'Make artistic skill irrelevant; collage and words count.'},
{type:'activity',tags:'food social office hybrid cooking tasting',name:'Global Snack & Story Table',why:'Food can create an easy conversation starter when participation and sharing are optional.',outcome:'Informal connection and learning about colleagues’ tastes or traditions.',min:6,max:20,time:'45–75 min',needs:['Snacks/catering','Ingredient/allergy labels','Tables','Optional story cards'],steps:['Ask volunteers to suggest snacks or choose a diverse catered selection.','Clearly label ingredients and dietary information.','Set small tables with one light prompt at each.','Invite people to share a short story about a food only if they want to.','End by collecting favorite discoveries for a future team lunch.'],tips:'Do not pressure employees to represent a culture or disclose personal background.'},
{type:'activity',tags:'volunteer volunteering community purpose off-site',name:'Team Volunteer Session',why:'A shared contribution can create meaning and connection when the cause and participation are chosen thoughtfully.',outcome:'Shared purpose and a different context for teamwork.',min:0,max:25,time:'Half day',needs:['Reputable local organization','Confirmed volunteer brief','Transport if needed'],steps:['Survey the team for causes they are comfortable supporting.','Contact a reputable organization and ask what help is genuinely useful.','Confirm accessibility, timing, transport and what the organization provides.','Brief employees on the activity and make participation voluntary.','Afterwards, share the organization’s impact update rather than centering the company.'],tips:'Choose work the partner organization actually needs; avoid turning volunteering into a photo opportunity.'},
{type:'activity',tags:'remote hybrid game social',name:'Remote Mystery Rooms',why:'Collaborative puzzles create a shared task for distributed teams without requiring work talk.',outcome:'Remote interaction, problem solving and playful teamwork.',min:0,max:12,time:'45–60 min',needs:['Video call','Shared slides/forms or a reputable virtual game provider','Breakout rooms'],steps:['Choose a simple puzzle pack or virtual provider appropriate to the team.','Split into groups of 4–6 and explain the rules clearly.','Use breakout rooms and give one hint channel.','Bring everyone back for the final answer and a short debrief.','Ask which puzzle style worked best before repeating.'],tips:'Avoid overly complex rules; remote activities work better when joining is frictionless.'}
];
function cur(){const c=document.querySelector('#currency')?.value||'EUR';return c==='Other'?(document.querySelector('#customCurrency')?.value.trim()||'¤'):c}
function money(n,c=cur()){const sym=symbols[c]||c+' ';return sym+Math.round(n)}
function estimate(item,size,c=cur()){let min=item.min*size,max=item.max*size;if(item.max===0)return money(0,c);return `${money(min,c)}–${money(max,c)}`}
function detailedCard(item,size){return `<div class="result"><h3>${item.name}</h3><div class="result-meta"><span class="pill budget-pill">Estimated budget: ${estimate(item,size)}</span><span class="pill">Time: ${item.time}</span></div><p class="why"><b>Why this fits:</b> ${item.why}</p><p class="outcome"><b>Expected outcome:</b> ${item.outcome}</p><p><b>What you’ll need:</b> ${item.needs.join(' · ')}</p><p><b>Step-by-step:</b></p><ol class="steps-list">${item.steps.map(s=>`<li>${s}</li>`).join('')}</ol><p class="tip"><b>Practical note:</b> ${item.tips}</p></div>`}
function scoreIdeas(type,text,format,budget,size){const words=text.toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>2);return ideaLibrary.filter(x=>x.type===type).map(x=>{let score=0;words.forEach(w=>{if((x.tags+' '+x.name+' '+x.why).toLowerCase().includes(w))score+=5});if((x.tags||'').toLowerCase().includes(format.toLowerCase()))score+=2;const mid=((x.min+x.max)/2)*size;if(mid<=budget*1.2)score+=2;return [score,x]}).sort((a,b)=>b[0]-a[0]).map(x=>x[1])}
function generate(tool){const size=+(document.querySelector('#teamSize')?.value||1),budget=+(document.querySelector('#budget')?.value||0),format=getChoice('format'),custom=document.querySelector('#challengeText')?.value.trim()||'';results.hidden=false;if(tool==='engagement'){const preset=document.querySelector('#challengePreset').value;const seed=(preset==='other'?'':preset+' ')+custom;const arr=scoreIdeas('engagement',seed,format,budget,size);renderIdeas('Your PeopleLab suggestions',arr,size,custom)}if(tool==='wellbeing'){const goal=document.querySelector('#goal').value;const own=document.querySelector('#goalOther').value.trim();const seed=(goal==='other'?own:goal+' '+own)+' '+custom;const arr=scoreIdeas('wellbeing',seed,format,budget,size);renderIdeas('Wellbeing ideas for your team',arr,size,[own,custom].filter(Boolean).join(' · '))}if(tool==='activity'){const seed=custom+' '+getChoice('time')+' '+format;const arr=scoreIdeas('activity',seed,format,budget,size);renderIdeas('Activities that fit your brief',arr,size,custom,true)}if(tool==='onboarding')createOnboarding();results.scrollIntoView({behavior:'smooth',block:'nearest'})}
function renderIdeas(title,arr,size,custom,more=false){const count=more?Math.min(8,arr.length):Math.min(6,arr.length);results.innerHTML=`<h3>${title}</h3>${custom?`<div class="custom-context"><b>Your context:</b> ${esc(custom)}</div>`:''}<p class="research-note">${evidenceNote}</p>${arr.slice(0,count).map(x=>detailedCard(x,size)).join('')}`}
function getChoice(id){const el=document.querySelector('#'+id);if(!el)return'';if(el.value!=='other'&&el.value!=='Other')return el.value;return document.querySelector('#'+id+'Other')?.value.trim()||'Other'}
async function createOnboarding(){
  const user=await ensureSession();
  if(!supabase||!user){results.hidden=false;results.innerHTML='<div class="result"><h3>Database connection needed</h3><p>Check your VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY and enable Anonymous Sign-Ins in Supabase Auth.</p></div>';return}
  const empInput={first:document.querySelector('#firstName').value.trim(),last:document.querySelector('#lastName').value.trim(),role:document.querySelector('#role').value.trim(),format:getChoice('format'),depth:getChoice('depth'),start:document.querySelector('#start').value||null,notes:document.querySelector('#challengeText').value.trim()};
  const {data:emp,error}=await supabase.from('employees').insert({user_id:user.id,first_name:empInput.first,last_name:empInput.last,role:empInput.role,work_setup:empInput.format,checklist_depth:empInput.depth,start_date:empInput.start,notes:empInput.notes}).select().single();
  if(error){showDbError(error);return}
  const tasks=buildTasks(empInput.role,empInput.format,empInput.depth,empInput.notes).map((t,i)=>({employee_id:emp.id,user_id:user.id,section:t.group,task_text:t.text,is_done:false,sort_order:i}));
  const {error:taskError}=await supabase.from('onboarding_tasks').insert(tasks);if(taskError){showDbError(taskError);return}
  await renderEmployee(emp.id);
}
function buildTasks(role,format,depth,notes){let groups=[['Before day one',[`Confirm contract, start details and first-day schedule for ${role}.`,`Prepare equipment and required system access for the ${format.toLowerCase()} setup.`,'Assign an onboarding buddy and send a welcome note.']],['Day one',[`Welcome the new ${role} and explain the first week at a glance.`,'Introduce the team, key partners and where to ask for help.','Cover essential tools, communication channels and workplace basics.']],['First week',['Schedule role training and job-shadowing where relevant.','Set clear first-week priorities and what “good” looks like.','Hold an end-of-week check-in: what is clear, confusing or missing?']],['First 30 days',['Agree on first-month goals with the manager.','Create introductions with important cross-functional partners.','Run a 30-day check-in on role clarity, workload, connection and support.']]];if(depth.toLowerCase().includes('light'))groups=groups.slice(0,3).map(g=>[g[0],g[1].slice(0,2)]);if(depth.toLowerCase().includes('detailed')){groups.splice(2,0,['Days 2–5',['Share team norms, recurring meetings and decision-making habits.','Provide role-specific documentation and examples of strong work.','Schedule two buddy check-ins during the first week.']]);groups.push(['30-day review',['Review progress against initial goals.','Ask what part of onboarding helped most and what was missing.','Agree on development priorities for the next 60 days.']])}if(notes)groups[0][1].push(`Role-specific setup: ${notes}`);return groups.flatMap(([group,items])=>items.map(text=>({group,text,done:false})))}
function pct(emp){const tasks=emp.tasks||[];return tasks.length?Math.round(tasks.filter(t=>t.is_done).length/tasks.length*100):0}
async function fetchEmployees(){const user=await ensureSession();if(!supabase||!user)return[];const {data,error}=await supabase.from('employees').select('*, onboarding_tasks(*)').order('created_at',{ascending:false});if(error){showDbError(error);return[]}return (data||[]).map(e=>({...e,tasks:(e.onboarding_tasks||[]).sort((a,b)=>a.sort_order-b.sort_order)}))}
async function renderEmployee(id){const all=await fetchEmployees(),emp=all.find(x=>x.id===id);if(!emp)return renderDashboard();const groups=[...new Set(emp.tasks.map(t=>t.section))];results.hidden=false;results.innerHTML=`<div class="employee-head"><div><button class="text-btn" onclick="renderDashboard()">← Dashboard</button><h3>${esc(emp.first_name)} ${esc(emp.last_name)} — ${esc(emp.role)}</h3><div class="result-meta"><span class="pill">${esc(emp.start_date||'No start date')}</span><span class="pill">${esc(emp.work_setup||'')}</span><span class="pill">${pct(emp)}% complete</span></div></div></div><div class="progress"><span style="width:${pct(emp)}%"></span></div><div class="checklist">${groups.map(g=>`<div class="check-group"><h3>${esc(g)}</h3>${emp.tasks.filter(t=>t.section===g).map(t=>`<label class="check-item"><input type="checkbox" ${t.is_done?'checked':''} onchange="toggleTask('${emp.id}','${t.id}',this.checked)"><span>${esc(t.task_text)}</span></label>`).join('')}</div>`).join('')}</div><div class="add-task"><h3>Add your own task</h3><input id="newTaskText" placeholder="e.g. Activate Beehive account"><input id="newTaskGroup" placeholder="Section, e.g. Before day one"><button class="secondary" onclick="addTask('${emp.id}')">Add task</button></div>`}
async function toggleTask(empId,taskId,done){const {error}=await supabase.from('onboarding_tasks').update({is_done:done,updated_at:new Date().toISOString()}).eq('id',taskId);if(error){showDbError(error);return}await renderEmployee(empId)}
async function addTask(empId){const text=document.querySelector('#newTaskText').value.trim(),section=document.querySelector('#newTaskGroup').value.trim()||'Custom tasks';if(!text)return;const user=await ensureSession();const {count}=await supabase.from('onboarding_tasks').select('*',{count:'exact',head:true}).eq('employee_id',empId);const {error}=await supabase.from('onboarding_tasks').insert({employee_id:empId,user_id:user.id,section,task_text:text,is_done:false,sort_order:count||0});if(error){showDbError(error);return}await renderEmployee(empId)}
async function renderDashboard(){results.hidden=false;results.innerHTML='<div class="empty">Loading onboarding records…</div>';const all=await fetchEmployees();const months={};all.forEach(e=>{const d=e.start_date||e.created_at.slice(0,10),m=d.slice(0,7);months[m]=(months[m]||0)+1});results.innerHTML=`<div class="dashboard-head"><div><h3>Onboarding inbox</h3><p>${all.length} employee record${all.length===1?'':'s'} saved in Supabase.</p></div></div>${Object.keys(months).length?`<div class="stats">${Object.entries(months).sort().reverse().slice(0,4).map(([m,n])=>`<div><b>${n}</b><span>${esc(m)} onboardings</span></div>`).join('')}</div>`:''}<div class="employee-list">${all.length?all.map(e=>`<button class="employee-row" onclick="renderEmployee('${e.id}')"><span><b>${esc(e.first_name)} ${esc(e.last_name)}</b><small>${esc(e.role)} · ${esc(e.start_date||'No date')}</small></span><span class="pct">${pct(e)}%</span></button>`).join(''):'<div class="empty">No onboarding records yet. Create your first employee above.</div>'}</div><p class="storage-note"><b>Cloud storage:</b> onboarding records and task progress are stored in your Supabase database and can be reopened later from this dashboard.</p>`;results.scrollIntoView({behavior:'smooth',block:'nearest'})}
function showDbError(error){console.error(error);results.hidden=false;results.innerHTML=`<div class="result"><h3>Supabase needs one more setup step</h3><p>${esc(error.message||String(error))}</p><p>If the message mentions anonymous sign-ins, open Supabase → Authentication → Sign In / Providers → Anonymous and enable it.</p></div>`}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
window.renderDashboard=renderDashboard;window.renderEmployee=renderEmployee;window.toggleTask=toggleTask;window.addTask=addTask;
